"""create task table

Revision ID: 80fbd44ec3ae
Revises: 9ffeea253add
Create Date: 2025-05-22 14:08:25.764367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80fbd44ec3ae'
down_revision: Union[str, None] = '9ffeea253add'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('createDate', sa.DateTime(timezone=True), nullable=False))
    op.add_column('tasks', sa.Column('lastEditDate', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'lastEditDate')
    op.drop_column('tasks', 'createDate')
    # ### end Alembic commands ###
