"""create task table

Revision ID: 9ffeea253add
Revises: dd112f637fb8
Create Date: 2025-05-22 12:19:21.188065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ffeea253add'
down_revision: Union[str, None] = 'dd112f637fb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('user', sa.String(length=50), nullable=False))
    op.add_column('tasks', sa.Column('category', sa.String(length=25), nullable=True))
    op.add_column('tasks', sa.Column('priority', sa.String(length=25), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'priority')
    op.drop_column('tasks', 'category')
    op.drop_column('tasks', 'user')
    # ### end Alembic commands ###
